/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/nutritionist-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diet` | `/diet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/objectives`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/personal`; params?: Router.UnknownInputParams; } | { pathname: `/settings/about`; params?: Router.UnknownInputParams; } | { pathname: `/settings/payment`; params?: Router.UnknownInputParams; } | { pathname: `/settings/plans`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/nutritionist-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/diet` | `/diet`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/objectives`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/personal`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/about`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/plans`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/edit-profile${`?${string}` | `#${string}` | ''}` | `/nutritionist-profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/diet${`?${string}` | `#${string}` | ''}` | `/diet${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exercises${`?${string}` | `#${string}` | ''}` | `/exercises${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/onboarding/objectives${`?${string}` | `#${string}` | ''}` | `/onboarding/personal${`?${string}` | `#${string}` | ''}` | `/settings/about${`?${string}` | `#${string}` | ''}` | `/settings/payment${`?${string}` | `#${string}` | ''}` | `/settings/plans${`?${string}` | `#${string}` | ''}` | `/settings/privacy${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/nutritionist-profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diet` | `/diet`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/objectives`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/personal`; params?: Router.UnknownInputParams; } | { pathname: `/settings/about`; params?: Router.UnknownInputParams; } | { pathname: `/settings/payment`; params?: Router.UnknownInputParams; } | { pathname: `/settings/plans`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
